apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-api
  template:
    metadata:
      labels:
        app: iot-api
    spec:
      containers:
      - name: iot-api
        image: yourdockerhubuser/iot-api:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: iot-api-service
spec:
  selector:
    app: iot-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort
